version: "3.7"

services:
  redis:
    restart: always
    container_name: redis
    image: redis:7.2.3-alpine
    volumes:
      - redis-data:/data

  postgres-data:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-data
    restart: always
    environment:
      POSTGRES_DB: ${DB_DASHBOARD_DBNAME}
      POSTGRES_USER: ${DB_DASHBOARD_USER}
      POSTGRES_PASSWORD: ${DB_DASHBOARD_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

      #放csv檔，啟動時會自動執行
      - ./ogdata/garbage_truck.csv:/docker-entrypoint-initdb.d/garbage_truck.csv

      #組件1&2_食安檢驗總覽/食安檢驗分佈
      - ./ogdata/food_inspections.csv:/docker-entrypoint-initdb.d/food_inspections.csv
      - ./ogdata/food_inspections_dist.csv:/docker-entrypoint-initdb.d/food_inspections_dist.csv

      #組件3_登革熱疫情概況
      - ./ogdata/dengue_invest.csv:/docker-entrypoint-initdb.d/dengue_invest.csv
      - ./ogdata/dengue_daily_case.csv:/docker-entrypoint-initdb.d/dengue_daily_case.csv

      #組件4_登革熱快篩資源分佈
      - ./ogdata/hosp_vaccine_info.csv:/docker-entrypoint-initdb.d/hosp_vaccine_info.csv

      #組件5_麻疹(漢他病毒)概況
      - ./ogdata/measles_case.csv:/docker-entrypoint-initdb.d/measles_case.csv

      #組件7_急救責任醫院分佈
      - ./ogdata/emergency_hospital.csv:/docker-entrypoint-initdb.d/emergency_hospital.csv

      #組件8_藥局分佈
      - ./ogdata/pharmacy.csv:/docker-entrypoint-initdb.d/pharmacy.csv

      #放table schema，啟動時會自動執行
      - ./ogdata/myData.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-manager:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-manager
    restart: always
    environment:
      POSTGRES_DB: ${DB_MANAGER_DBNAME}
      POSTGRES_USER: ${DB_MANAGER_USER}
      POSTGRES_PASSWORD: ${DB_MANAGER_PASSWORD}
    volumes:
      - postgres-manager-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "8889:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP/gRPC 接口預設埠
      - "6334:6334" # 複製／分片關係預設埠（如有需要）
    volumes:
      - qdrant-data:/qdrant/storage # 持久化資料儲存
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__WAL_ENABLED=true
      - QDRANT__STORAGE__WAL_PATH=/qdrant/storage/wal
      - QDRANT__STORAGE__SIZE_LIMIT=20GB # 預估大小，依需求調整
      # 啟用 API key 驗證
      - QDRANT__SERVICE__API_KEY_ENABLED=true
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}

networks:
  default:
    name: br_dashboard
    external: true

volumes:
  redis-data:
    name: redis_data
  postgres-data:
    name: postgres_data
  postgres-manager-data:
    name: postgres_manager_data
  pgadmin-data:
    name: pgadmin_data
  qdrant-data:
    name: qdrant_data
